from darwin.db.client import (
    DATABASE_NAME,
    close_client,
    get_client,
    get_db,
    watch_collection,
)
from darwin.db.indexes import VECTOR_INDEXES, ensure_collections, ensure_indexes
from darwin.db.schemas import (
    COLLECTION_CHAMPIONS,
    COLLECTION_CHUNKS,
    COLLECTION_FITNESS_EVALUATIONS,
    COLLECTION_GENERATIONS,
    COLLECTION_GENOMES,
    COLLECTION_QUERIES,
    Champion,
    Chunk,
    CoordinationGenes,
    EmbeddingModel,
    FitnessComponents,
    FitnessEvaluation,
    Generation,
    GenerationGenes,
    Genome,
    GenomeStatus,
    Query,
    RetrievalGenes,
)

__all__ = [
    "DATABASE_NAME",
    "VECTOR_INDEXES",
    "COLLECTION_CHAMPIONS",
    "COLLECTION_CHUNKS",
    "COLLECTION_FITNESS_EVALUATIONS",
    "COLLECTION_GENERATIONS",
    "COLLECTION_GENOMES",
    "COLLECTION_QUERIES",
    "Champion",
    "Chunk",
    "CoordinationGenes",
    "EmbeddingModel",
    "FitnessComponents",
    "FitnessEvaluation",
    "Generation",
    "GenerationGenes",
    "Genome",
    "GenomeStatus",
    "Query",
    "RetrievalGenes",
    "close_client",
    "ensure_collections",
    "ensure_indexes",
    "get_client",
    "get_db",
    "watch_collection",
]
